### ISSUE TITLE
Turn on CodeQL scanning

### ISSUE THREAD

**Issue by dpogue** [dpogue/seymour#31]
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository

GitHub has a new security scanning tool that's available through GitHub Actions. It looks pretty easy to set up, would be nice to integrate into the existing PR and CI runs.

**Comment by MaximeKoitsalu** [comment]
Hi @dpogue I'd gladly take on this task
