### ISSUE TITLE
Documentation: SEY_BUILD_TYPE => SEY_BUILD_MODE

### ISSUE THREAD

**Issue by MikeDimmickMnetics** [dpogue/seymour#64]
The SEY_BUILD_TYPE environment variable does not work - no matter how it is set, you get a debug build.

Looking at the code, I can see that a variable SEY_BUILD_MODE will, if set to 'release', produce a release build. Otherwise you get a debug build.

Please update the documentation with the correct variable name.

Tested on v2.1.0, since I'm trying to add Seymour to a Cordova 7.1.0 project, but it looks like this is also the case in v5.0.0.

**Comment by dpogue** [comment]
Oops! Thanks for catching this!

I've updated the README to reflect the correct variable name (which is `SEY_BUILD_MODE`, as you noted)
